### ISSUE TITLE
Have issue with Callback I can not figure out

### ISSUE THREAD

**Issue by gsmatth** [codefellows/seattle-javascript-401n1#65]
I canno tfigure out why I am getting an error stating that : "/Users/djp/401/lab-03-fs-async/lab-doug/lib/showContents.js:32
      printContents(fileName);
      ^

TypeError: printContents is not a function
    at /Users/djp/401/lab-03-fs-async/lab-doug/lib/showContents.js:32:7
    at FSReqWrap.oncomplete (fs.js:82:15)"

code snippet:

function showContents(printContents){
  fs.readdir(__dirname + '/../docs/', function(err, files){
    for(var i = 0; i < files.length; i++){
      console.log('file.length in for loop is: '+  files.length);
      var fileName = files[i];
      console.log('value of fileName: ' + fileName);
      printContents(fileName);
    }
  });
}
showContents(function(fileName){
  fs.readFile(__dirname + '/../docs/' + fileName,'hex', function(err, data){
    if(err) throw err;
    console.log ('The data is: ' + data);
  });
});

**Comment by gsmatth** [comment]
looks like I worked through that issue(needed an extra set of parenthesis at the end of where I called  showContents.  No I have same issue I had 24hours ago.  I cannot successfully pass the current fileName value as a parameter of the callback:


the value of fileName in printContents callback is: undefined
/Users/djp/401/lab-03-fs-async/lab-doug/lib/showContents.js:39
    if(err) throw err;
            ^

Error: ENOENT: no such file or directory, open '/Users/djp/401/lab-03-fs-async/lab-doug/lib/../docs/undefined'
    at Error (native)

**Comment by gsmatth** [comment]
I figured out my problem was that I was calling my function outside the original function.  I think I can solve this now.
